# SPDX-FileCopyrightText: 2013-2022 Miguel Gonzalez <migonzalvar@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v3.1.0a1
    hooks:
      - id: reuse
