---
name: CI

on: [push]

env:
  FORCE_COLOR: "1"
  PYTHON_LATEST: "3.10"

jobs:
  tests:
    name: tox on ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox tox-gh-actions

      - name: Test with tox
        run: tox

      - name: Check coverage
        run: tox -e coverage-report
        if: ${{ matrix.python-version == env.PYTHON_LATEST }}
